// Generated by CoffeeScript 1.4.0

define(function() {
  var AIPlayer;
  return AIPlayer = (function() {

    AIPlayer.prototype.color = 2;

    function AIPlayer(params) {
      var k, v;
      for (k in params) {
        v = params[k];
        this[k] = v;
      }
      if (!(this.game != null)) {
        throw new Error('no game reference was given to create the state object!');
      }
    }

    AIPlayer.prototype.makeMove = function() {
      var move;
      move = this.game.aistate.findBestMove();
      if (!(move.tile != null)) {
        move = this.game.aistate.findBestMove(true);
      }
      this.game.user.tile = move.tile;
      this.game.triggers.movemade.call(this.game, move);
      return console.log('ai plays', [move.x, move.y], 'with tile', move.tile);
    };

    AIPlayer.prototype.makeSnarkyRemark = function() {};

    return AIPlayer;

  })();
});
