
define(function() {
  var Avatar;
  return Avatar = (function() {

    Avatar.prototype.image = null;

    function Avatar(params) {
      var k, v;
      for (k in params) {
        v = params[k];
        this[k] = v;
      }
    }

    return Avatar;

  })();
});

// Generated by CoffeeScript 1.5.0-pre
