// Generated by CoffeeScript 1.4.0
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['core/placetiles'], function(placeTiles) {
  var CELLSIZE, Kulami, MoveTile;
  CELLSIZE = 32;
  MoveTile = (function() {

    MoveTile.prototype.size = null;

    MoveTile.prototype.x = 0;

    MoveTile.prototype.y = 0;

    MoveTile.prototype.w = 1;

    MoveTile.prototype.h = 1;

    function MoveTile(params) {
      var k, sides, v;
      for (k in params) {
        v = params[k];
        this[k] = v;
      }
      if (this.size != null) {
        sides = this.size.split('x');
        if (sides[0] > sides[1]) {
          this.w = sides[0];
          this.h = sides[1];
        } else {
          this.w = sides[1];
          this.h = sides[0];
        }
      }
    }

    return MoveTile;

  })();
  return Kulami = (function(_super) {

    __extends(Kulami, _super);

    Kulami.prototype.mode = 'placetiles';

    Kulami.prototype.tiles = [];

    function Kulami() {
      this.tiles = [
        new MoveTile({
          size: '2x2'
        }), new MoveTile({
          size: '3x1'
        }), new MoveTile({
          size: '2x1'
        }), new MoveTile({
          size: '3x2'
        })
      ];
    }

    Kulami.prototype.draw = function() {
      return atom.context;
    };

    return Kulami;

  })(atom.Game);
});
