// Generated by CoffeeScript 1.4.0

define(['core/util', 'core/atom', 'core/game'], function(_util, _atom, Kulami) {
  var isPreloadComplete, loaded, startGame;
  startGame = function() {
    return (new Kulami()).run();
  };
  loaded = {
    gfx: false,
    sfx: false
  };
  isPreloadComplete = function() {
    if (loaded.gfx && loaded.sfx) {
      startGame();
      return true;
    } else {
      return false;
    }
  };
  atom.preloadImages({
    cell_: 'cell_.png',
    cell_red: 'cell_red.png',
    cell_black: 'cell_black.png',
    button_random: 'button_random.png',
    button_help: 'button_help.png',
    button_play: 'button_play.png'
  }, function() {
    loaded.gfx = true;
    return isPreloadComplete();
  });
  atom.preloadSounds({
    crack: 'crack.mp3',
    pick: 'pick.mp3',
    drop: 'drop.mp3'
  }, function() {
    loaded.sfx = true;
    return isPreloadComplete();
  });
});
