
define(['core/util', 'core/atom', 'core/game'], function(_util, _atom, Kulami) {
  var isPreloadComplete, loaded, startGame;
  startGame = function() {
    var g;
    g = new Kulami();
    g.run();
    return window.poo = g;
  };
  loaded = {
    gfx: false,
    sfx: false
  };
  isPreloadComplete = function() {
    if (loaded.gfx && loaded.sfx) {
      startGame();
      return true;
    } else {
      return false;
    }
  };
  atom.preloadImages({
    ball: 'ball.png'
  }, function() {
    loaded.gfx = true;
    return isPreloadComplete();
  });
  atom.preloadSounds({
    crack: 'crack.mp3'
  }, function() {
    loaded.sfx = true;
    return isPreloadComplete();
  });
});

// Generated by CoffeeScript 1.5.0-pre
