// Generated by CoffeeScript 1.4.0

define(function() {
  var Instructions;
  return Instructions = (function() {

    Instructions.prototype.NEUTRAL_BOARDSETUP = {
      text: 'Drag the tiles to form a board.\nA illegaly placed tile becomes translucent.\nHit the GO button to start the game.',
      audio: null
    };

    Instructions.prototype.BAD_BOARDINVALID = {
      text: 'Illegal board layout!',
      audio: null
    };

    Instructions.prototype.NEUTRAL_GAMERULES1 = {
      text: 'This game is won by scoring.\nA player who owns the most cells wins.\nOn each turn, a player places a marble in an empty spot on a tile.',
      audio: null
    };

    Instructions.prototype.NEUTRAL_GAMERULES2 = {
      text: 'A tile (and its entire collection of cells) is owned by a player when the majority of its marbles are that player\'s color.\nOn each turn, a player places a marble in an empty spot on a tile.',
      audio: null
    };

    Instructions.prototype.type = 'text';

    Instructions.prototype.game = null;

    function Instructions(params) {
      var k, v;
      for (k in params) {
        v = params[k];
        this[k] = v;
      }
    }

    return Instructions;

  })();
});
