// Generated by CoffeeScript 1.4.0

define(['core/mobileDetect'], function(detectMobile) {
  if (window.isMobile != null) {
    require(['howler'], function(l) {
      var mobileSound;
      mobileSound = new Howl({
        urls: ['sfx/sprite.mp3'],
        sprite: {
          crack: [0, 534],
          pick: [32670, 145],
          drop: [569, 296],
          invalid: [32520, 151],
          valid: [32839, 198],
          r_damn: [33215, 572],
          r_damnit: [34076, 749],
          r_disturbing: [34996, 2986],
          r_excellent: [38231, 1086],
          r_fate: [39448, 2079],
          r_good: [41527, 1034],
          r_haha: [42561, 883],
          r_hmm: [43663, 503],
          r_longenough: [44316, 1498],
          r_slow: [46068, 1739]
        }
      });
      atom.playSound = function() {
        return mobileSound.play.apply(mobileSound, arguments);
      };
      atom.stopAllSounds = function() {
        return mobileSound.stop.apply(mobileSound);
      };
    });
    window.onorientationchange = function() {
      window.onresize();
      if (window.orientation === 0) {
        window.game.triggers.verticalorientation.call(window.game);
      } else {
        window.game.triggers.horizontalorientation.call(window.game);
      }
    };
  }
});
