// Generated by CoffeeScript 1.4.0

define(['core/mobileDetect'], function(detectMobile) {
  if (window.isMobile != null) {
    require(['howler'], function(l) {
      var mobileSound;
      mobileSound = new Howl({
        urls: ['sfx/sprite.mp3'],
        sprite: {
          crack: [0, 534],
          pick: [32670, 145],
          drop: [569, 296],
          invalid: [32520, 151],
          valid: [32839, 198],
          gamerules1: [1022, 9056],
          gamerules2: [10263, 5155],
          gamerules3: [15465, 13050],
          gamerules4: [28514, 3994]
        }
      });
      atom.playSound = function() {
        return mobileSound.play.apply(mobileSound, arguments);
      };
    });
    window.onorientationchange = function() {
      window.onresize();
      if (window.orientation === 0) {
        window.game.triggers.verticalorientation.call(window.game);
      } else {
        window.game.triggers.horizontalorientation.call(window.game);
      }
    };
  }
});
